Titulo do Trabalho;Prof. Dr. Ruben Carlo Benante;rcb@beco.cc;0;beco;@drbeco;;0;
8;10;8;8;10;10;10;Juan Kalebe Andrade Da Silva;jkas@poli.br;jkas;@juankalebe;m
8;8;8;10;10;10;10;Yasmim Silva Maciel;yasmim.maciel@upe.br;ysm;@yasmimsmaciel;s
8;8;8;8;8;8;8;Kauwane Fidelis De Souza;kfs1@poli.br;kfs1;@Kauwanefideliss;s
8;10;10;10;9;8;9;Alline Heveline Bezerra Gaiao;alline.gaiao@upe.br;ahbg;@AllineGaiao;s
8;9;10;9;9;10;9;Carmen Lucia Layme Dantas Da Silva;carmen.layme@upe.br;clldds;@carmenlayme-ux;s
8;8;8;8;8;8;8;Hugo Smith Branquinho;hugo.branquinho@upe.br;hsb;@hugobranquinho1;s
8;8;8;8;8;8;8;Victor De Lima Melo;victor.limamelo@upe.br;vdlm;@vict0r-mel0;s
8;8;8;8;8;8;8;Lucas Heitor Rodrigues De Alcantara Velho Barretto;lucas.heitor@upe.br;lhrdavb;@lucasheitor-beep;s
8;8;8;8;8;8;8;Sandro Goncalves Da Silva Filho;sandro.silvafilho@upe.br;sgdsf;@SANDROSILVAFILHO;s
